name:           Sergio's Blog
description:    Software dev experiences
url:            http://sergioalvarezsuarez.com
markdown:       redcarpet
highlighter:    pygments
paginate:       5
paginate_path:  "blog/page:num"

sass:
  style: :compressed

gems:
  - jemoji
  - jekyll-sitemap
