name:           Sergio Álvarez-Suárez
description:    Software Engineer
url:            http://sergioalvz.com
markdown:       redcarpet
highlighter:    pygments

exclude: [Gemfile, Gemfile.lock]

sass:
  style: :compressed

plugins:
  - jemoji
  - jekyll-sitemap
