name:           Sergio's Blog
description:    Software dev experiences
url:            http://sergioalvarezsuarez.com
markdown:       redcarpet
pygments:       true
paginate:       10
paginate_path:  "archive/page:num"
