name:           Sergio's Blog
description:    Software dev experiences
url:            http://sergioalvarezsuarez.com
markdown:       redcarpet
highlighter:    pygments
paginate:       10
paginate_path:  "archive/page:num"

gems:
  - jemoji
  - jekyll-sitemap
